name: ABMCMergedSpawners
main: server.alanbecker.net.Main
author: MasterGabeMOD
version: 1.0
api-version: 1.20
permissions:
  abmc.spawnermerge:
    description: Allows players to merge spawners.
    default: true
